In [1]:
import torch

使用`arange`创建一个行向量`x`

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过张量的`shape`属性来访问张量a

In [4]:
x.shape

torch.Size([12])

张量中的元素总数

In [5]:
x.numel()

12

改变一个张量的形状而不改变数量和元素值，可以调用`reshape`函数

In [6]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

初始化矩阵

In [5]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

初始化矩阵的值

In [6]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

从某个特定的概率分布中随机采样来得到张量中每个元素的值

In [7]:
torch.randn(3, 4)

tensor([[ 1.0218, -0.0090, -0.0900,  1.8066],
        [ 0.6204,  0.7068, -0.4008, -0.4972],
        [ 0.5434, -1.1991,  0.3364,  0.7682]])

## 运算符

In [8]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [9]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
X, Y

(tensor([[158., 151., 172., 165.],
         [151., 158., 165., 172.],
         [124., 129., 134., 139.]]),
 tensor([[66., 63., 72., 69.],
         [63., 66., 69., 72.],
         [52., 54., 56., 58.]]))

In [ ]:
X == Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
X > Y, X < Y

(tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [ ]:
X.sum()

tensor(66.)

In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))

X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [16]:
c = torch.arange(9).reshape((3, 3))
d = torch.arange(9).reshape((3, 3))

c, d

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]))

In [17]:
c + d

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [20]:
X[-1],  X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [22]:
X[1, 2] = 9

X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X[0:2, :] = 12

X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [28]:
before = id(Y)

Y = Y + X

id(Y) == before


False

In [25]:
Z = torch.zeros_like(Y)
print('id(Z): ', id(Z))

Z[:] = X + Y
print('id(Z): ', id(Z))

id(Z):  140324046063792
id(Z):  140324046063792


In [26]:
before = id(X)
X += Y

id(X) == before

True

In [29]:
A = X.numpy()
B = torch.tensor(A)

type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [30]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)